latest_techmelange/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp.views import *
from myapp  import views

urlpatterns = [
    path("",LandingPageView.as_view(), name="home"),
    path("about-us/", AboutUsView.as_view(), name="about-us"),
    path("events/", EventsView.as_view(), name="events"),
    path("eventTimeline/", EventsTimelineView.as_view(), name="event-timeline"),
    path("event/event_id=<event_id>/", EventView.as_view(), name="event"),
    path("student-council/", StudentCouncilView.as_view(), name="student-council"),
    path("contact/", ContactView.as_view(), name="contact")


    
]

myapp/models.py
from operator import truediv
from ckeditor_uploader.fields import RichTextUploadingField
from statistics import mode
import uuid
from django.db import models
from enum import Enum

class ChoiceEnum(Enum):
    @classmethod
    def get_value(cls, member):
        return cls[member].value[0]

    @classmethod
    def get_choices(cls):
        return tuple(x.value for x in cls)


class PositionType(ChoiceEnum):
    president = ('P', 'President')
    vicePresident = ('R', 'Vice President')
    secretary = ('S', 'Secretary')
    treasurer = ('T', 'Treasurer')
    joint_secretary = ('JS', 'Joint Secretary')
    joint_treasurer = ('JT', 'Joint Treasurer')
    coordinator = ('C', 'Coordinator')
    member = ('M', 'Member')


class BaseModel(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class TechFest(BaseModel):
    name = models.CharField(max_length=100)
    short_description = models.CharField(max_length=600)
    description = models.TextField()
    society_logo = models.ImageField(null=True)
    college_logo= models.ImageField(null=True)
    university_logo=models.ImageField(null=True)
    fest_image=models.ImageField(null=True)
    fest_video = models.FileField(null =True)
    start_date = models.DateField()
    end_date = models.DateField()
    email = models.CharField(max_length=50)
    instagram = models.CharField(max_length=50)
    linkedin = models.CharField(max_length=50)
    facebook = models.CharField(max_length=50)
    twitter = models.CharField(max_length=50)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Tech Fest'
        verbose_name = 'Tech Fest'

    def __str__(self):
        return self.name

class Events(BaseModel):
    name = models.CharField(max_length=100)
    short_description = models.CharField(max_length=100)
    description = RichTextUploadingField(config_name='portal_config')
    rules = RichTextUploadingField(config_name='portal_config')
    event_start_date = models.DateField()
    event_end_date = models.DateField()
    stages = models.IntegerField()
    event_start_time = models.TimeField()
    event_end_time = models.TimeField()
    event_image = models.ImageField(upload_to="event/images", null=True)
    event_video = models.FileField(upload_to="event/videos", null=True)
    link =  models.TextField(null=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Events'
        verbose_name = 'Event'

    def __str__(self):
        return self.name


class StudentCoordinators(BaseModel):
    event = models.ForeignKey(Events, on_delete=models.CASCADE, related_name='event_student_coordinators')
    name = models.CharField(max_length=100)
    image =  models.ImageField(upload_to="event/student_coordinators_images", null=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Student Coordinators'
        verbose_name = 'Student Coordinator'

    def __str__(self):
        return self.name


class TeacherCoordinators(BaseModel):
    event = models.ForeignKey(Events, on_delete=models.CASCADE, related_name='event_teacher_coordinators')
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100,null=True)
    image= models.ImageField(upload_to="event/teacher_coordinator_images", null=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Teacher Coordinators'
        verbose_name = 'Teacher Coordinator'

    def __str__(self):
        return self.name


class Speakers(BaseModel):
    name = models.CharField(max_length=100)
    image =  models.ImageField(upload_to="event/speakers_images", null=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Speakers'
        verbose_name = 'Speaker'

    def __str__(self):
        return self.name


class Sponsors(BaseModel):
    name = models.CharField(max_length=100)
    image= models.ImageField(upload_to="event/sponsors_images", null=True)
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Sponsors'
        verbose_name = 'Sponsor'

    def __str__(self):
        return self.name


class StudentCouncilMembers(BaseModel):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=50,choices=PositionType.get_choices())
    image= models.ImageField(upload_to="event/student_council_images", null=True)
    is_design_team= models.BooleanField(default=False)
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Student Council Members'
        verbose_name = 'Student Council'

    def __str__(self):
        return self.name

class EventsTimeLine(BaseModel):
    name = models.CharField(max_length=100, null=True)
    content = RichTextUploadingField(config_name='portal_config')
    class Meta:
        verbose_name_plural = 'Event TimeLine'
        verbose_name = 'Event TimeLine'

myapp/views.py
from http.client import HTTPResponse
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View

from myapp.models import *

# Create your views here.

class LandingPageView(View):
    template_name = 'index.html'

    def get(self, request, **kwargs):
        techFest = TechFest.objects.all()
        events = Events.objects.all()
        speakers = Speakers.objects.all()
        sponsors = Sponsors.objects.all()
        return render(request, template_name="index.html", context={'techFest': techFest,'events':events,'speakers':speakers,'sponsors':sponsors})

class AboutUsView(View):
    template_name = 'about-us.html'

    def get(self, request, **kwargs):
        techFest = TechFest.objects.all()
        return render(request, template_name="about-us.html", context={'techFest': techFest})


class StudentCouncilView(View):
    template_name = 'student-council.html'

    def get(self, request, **kwargs):
        studentCouncil = StudentCouncilMembers.objects.filter(is_design_team=False).order_by('created_at')
        designTeam= StudentCouncilMembers.objects.filter(is_design_team=True).order_by('created_at')
        return render(request, template_name="student-council.html", context={'studentCouncil' : studentCouncil,'designTeam' : designTeam})
    
class ContactView(View):
    template_name = 'contact.html'

    def get(self, request, **kwargs):
        techFest = TechFest.objects.all()
        return render(request, template_name="contact.html", context={'techFest': techFest})

class EventsView(View):
    template_name = 'events.html'

    def get(self, request, **kwargs):
        events = Events.objects.all()
        return render(request, template_name="events.html", context={'events':events})

class EventView(View):
    template_name = 'event.html'

    def get(self, request, **kwargs):
        event = Events.objects.get(id=kwargs['event_id'])
        studentCoordinators= StudentCoordinators.objects.filter(event= event.id)
        teacherCoordinators= TeacherCoordinators.objects.filter(event= event.id)
        return render(request, template_name="event.html", context={'event':event,'studentCoordinators':studentCoordinators,'teacherCoordinators':teacherCoordinators})


class EventsTimelineView(View):
    template_name = 'event-timeline.html'

    def get(self, request, **kwargs):
        eventTimeline = EventsTimeLine.objects.all()
        return render(request, template_name="event-timeline.html", context={'eventTimeline':eventTimeline})

templates/about-us.html
{% extends "base.html" %}
{% block title %}
About Us
{% endblock title %}
{% block content %}
{% for i in techFest %}
<div class="row">
    <div class="col-6 offset-3">
        <div style="font-size: 50px;"><b>About Us</b></div>
        <div style="font-size: 18px;">{{ i.description|safe|escape }}</div>
    </div>
</div>
{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <title>Tech Melange</title>
    <style>
        html,
        body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            overflow-x: hidden;
            font-family: 'Times New Roman', Times, serif;
            min-height: 100%;
            font-size: 18px;
        }
        
        .mynavbar {
            height: 120px;
        }
        
        .navbar-img {
            height: 100px;
            width: 100px;
            border-radius: 100px;
        }
        
        .navbar-heading {
            font-size: 40px;
            font-family: 'Times New Roman', Times, serif;
            font-weight: 500;
            line-height: 0;
        }

        .navbarNav {
            justify-content: end;
        }
        
        .navbar-nav>li {
            padding-left: 30px;
            padding-right: 30px;
        }
        
        .college-logo {
            height: 150px;
            width: 150px;
            margin-left: 50px;
            margin-top: 20px;
        }
        
        .university-logo {
            width: 200px;
            height: 200px;
            margin-right: 30px;
            margin-top: 0px;
        }
        
        .first-part-heading {
            margin-top: 70px;
            font-family: 'Times New Roman', Times, serif;
            font-size: 45px;
        }
        
        .second-part {
            justify-content: center;
            text-align: center;
            font-size: 30px;
            font-family: "Sofia", sans-serif;
            color: darkblue;
            margin-left: 100px;
            margin-right: 100px;
        }
        
        .third-part-video {
            width: 93%;
            height: 700px;
            margin-left: 50px;
            margin-top: 100px;
        }
        
        .fourth-part-first-col {
            margin-left: 50px;
        }
        
        .fourth-part-second-col {
            text-align: right;
        }
        
        .about-us {
            margin-top: 75px;
            margin-left: 50px;
            font-size: 50px;
            font-weight: 500;
            font-family: 'Times New Roman', Times, serif;
        }
        
        .about-us-description {
            margin-left: 50px;
            margin-right: 50px;
            font-size: 20px;
            font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        }
        
        .read-more-btn {
            border-radius: 0;
            background-color: #00BFFF;
            border-color: #00BFFF;
            font-size: 15px;
            padding-left: 30px;
            padding-right: 30px;
            padding-top: 15px;
            padding-bottom: 15px;
        }
        
        .main-content {
            text-align: center;
        }
        
        .mylastbar {
            height: 80px;
        }
        .centered {
            position: fixed;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            font-size: 40px;
        }
        .add-spacing{
            margin-left:100px;
            margin-right:100px;
        }
        .heading-1{
            font-size: 50px;
        }
        .text-size{
            font-size:30px;
        }
        .text-size-small{
            font-size:20px;
        }
</style>
</head>

<body>
    {% include 'navbar.html' %}
    {% block content %}{% endblock content %}
    {% include 'footer.html' %}
</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% block title %}
Contact Us
{% endblock title %}
{% block content %}

{% for i in techFest %}
<div class="main-content mx-5" style="margin-bottom: 4%;">
    <span class="heading-1"><b>Contact Us</b></span><br>
    <div class=" text-size mt-3">
        In case of any queries, contact us on<br><i class="bi bi-envelope-fill"> {{ i.email }}</i><br>
        You can also reach us through the mentioned social medias<br>
        <i class="bi bi-instagram"> {{ i.instagram }}</i><br>
        <i class="bi bi-linkedin"> {{ i.linkedin }}</i><br>
        <i class="bi bi-facebook"> {{ i.facebook }}</i><br>
        <i class="bi bi-twitter"> {{ i.twitter }}</i>
    </div>   
</div>
{% endfor %}
{% endblock %}
   

templates/event-timeline.html
{% extends "base.html" %}
{% block title %}
Home
{% endblock title %}
{% block content %}
<div class="main-content text-size-small">
   <div class="row mt-5">
       <div class="col-8 offset-2">
        {% for i in eventTimeline %}
        {{ i.content|safe }}
        {% endfor %}
       </div>
   </div>  
</div>

{% endblock %}

templates/event.html
{% extends "base.html" %}
{% block title %}
Home
{% endblock title %}
{% block content %}
<div class="main-content">
  <span><b>{{ event.name }}</b></span><br>
  <video width="1180" height="480" controls autoplay>
    <source src="{{ event.event_video.url }}" type="video/mp4">
  </video>
  <br>
  <div class="row">
    <div class="col offset-1 text-justify ">
      <span class="heading-1"><b>Description</b></span><br>
      <p>
        {{ event.description }}
      </p>
    </div>
    <div class="col pr-0 mr-0">
      <img src="{{ event.event_image.url }}" width="95%" height="100%"><br>   
    </div>
    <div class="col-1"></div>
    <div class="row text-justify">
      <div class="col-10 offset-1" style="width:90%">
        <span class="heading-1"><b>Rules</b></span><br>
        {{ event.rules }}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-4 offset-4 mt-5">
      <button type="button" class="btn btn-primary btn-lg read-more-btn text-size-small"><a href="https://{{ event.link }}"  target="_blank" style="color:white;">Register Now</a></button>
  
    </div>
  </div>
  <br>
  <span class="heading-1"><b>Student Coordinators</b></span><br>
  <div>
    {% for s in studentCoordinators %} 
    <div class="add-spacing" style="display:inline-block;">
        <img src="{{ s.image.url }}" style="height: 250px;width:250px;border-radius: 150px;"><br>
        <p class="text-size-small mt-3">{{ s.name }}</p>
    </div>
    {% endfor %}
</div>
<span class="heading-1"><b>Teacher Coordinators</b></span><br>
<div>
  {% for t in teacherCoordinators %} 
  <div class="add-spacing" style="display:inline-block;">
      <img src="{{ t.image.url }}" style="height: 250px;width:250px;border-radius: 150px;"><br>
      <p class="text-size-small mt-3">{{ t.name }}<br>{{ t.position }}</p>
  </div>
  {% endfor %}
</div>
</div>
{% endblock %}

templates/events.html
{% extends "base.html" %}
{% block title %}
Home
{% endblock title %}
{% block content %}
    <div class="main-content">
        <span class="heading-1"><b>Events</b></span><br>
        {% for event in events %} {% if forloop.counter|divisibleby:"4" %}
        <br> {% endif %}
        <div style="display:inline-block;">
            <img src="{{ event.event_image.url }}" style="height: 400px;width:400px;padding:30px;"><br>
            <button type="button" class="btn btn-primary btn-lg read-more-btn;text-size-small"><a href="{% url 'event' event.id %}" style="color:white">Read More</a></button>
        </div>
        {% endfor %}
    </div>

{% endblock %}

templates/footer.html
<nav class="navbar navbar-light bg-light navbar-expand-lg mylastbar" style="position:relative;bottom:0;">
    <div style="margin-left: 100px;text-align: left;margin-top: 15px;">
        <span style="line-height: 0;">Copyright(c) TechMelange 2022</span>
        <span style="line-height: 0;margin-left:900px;">Powered by TechMelange</span>
    </div>
</nav>

templates/index.html
{% extends "base.html" %}
{% block title %}
Home
{% endblock title %}
{% block content %}
{% for i in techFest %}
    <div class="first-part row">
        <div class="col">
            <img class="college-logo" src="{{i.college_logo.url }}">
        </div>
        <div class="col">
            <h1 class="text-uppercase first-part-heading"><b>{{ i.name }}</b></h1>
        </div>
        <div class="col" style="text-align: right; padding: 0;">
            <img class="university-logo" src="{{i.university_logo.url }}">
        </div>
    </div>
    <div class="second-part row">
        {{ i.short_description }}
    </div>
    <div class="third-part row">
        <video class="third-part-video" width="320" height="240" controls>
            <source src="{{i.fest_video.url }}" type="video/mp4">
          </video>
    </div>
    <div class="fourth-part row mt-5">
        <div class="col-7 fourth-part-first-col bg-light">
            <p class="about-us text-uppercase">
                About Us
            </p>
            <p class="about-us-description">
                {{ i.description|striptags|linebreaksbr|truncatewords:117 }}
            </p>
            <div style="text-align:center;margin-top:50px;">
                <a href="about-us/"><button type="button" class="text-size-small btn btn-primary btn-lg read-more-btn">Read More</button></a>
            </div>
        </div>
        <div class="col-4 fourth-part-second-col">
            <img src="{{i.fest_image.url }}">
        </div>
    </div>
    <div class="main-content mt-5">
        <h1 class="heading-1 text-uppercase">Events</h1>
    </div>
    <div class="main-content mt-5">
        {% for event in events %} {% if forloop.counter|divisibleby:"4" %}
        <br> {% endif %}
        <div style="display: inline-block;">
            <img src="{{ event.event_image.url }}" style="height: 400px;width:400px;padding:30px;"><br>
            <button type="button" class="btn btn-primary btn-lg read-more-btn text-size-small"><a href="{{ event.link }}"  style="color: white;">Register Now</a></button>
        </div>
        {% endfor %}
    </div>

    <div class="main-content mt-5">
        <h1 class="heading-1 text-uppercase">Speakers</h1>
    </div>
    <div class="main-content">
        {% for speaker in speakers %} {% if forloop.counter|divisibleby:"4" %}
        <br> {% endif %}
        <div class="add-spacing" style="display:inline-block;">
            <img src="{{ speaker.image.url }}" style="height: 250px;width:250px;border-radius: 150px;"><br>
            <p class="text-size-small mt-3">{{ speaker.name }}</p>
        </div>
        {% endfor %}
    </div>
    <div class="main-content mt-5">
        <h1 class="heading-1 text-uppercase">Media Partners and Sponsors</h1>
    </div>
    <div class="main-content">
        {% for sponsor in sponsors %} {% if forloop.counter|divisibleby:"4" %}
        <br> {% endif %}
        <div class="add-spacing" style="display:inline-block;">
            <img src="{{ sponsor.image.url }}" style="height: 250px;width:250px;border-radius: 150px;"><br>
            <p class="text-size-small mt-3">{{ sponsor.name }}</p>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% endblock %}
   

templates/navbar.html
{% load static %}   
<nav class="navbar navbar-light bg-light navbar-expand-lg mynavbar"> 
        <img class="navbar-img" src="{{ MEDIA_URL }}/media/eniac.jpeg">
        <div class="mt-3 ml-2">
            <span class="navbar-heading"><b>Tech Melange</b></span><br>
            <span class="text-uppercase">Most Awaited Technical Fest</span>
        </div>
        <div class="collapse navbar-collapse navbarNav">
            <ul class="navbar-nav navbar-links">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'about-us' %}">About Us</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'event-timeline' %}">Event Timeline</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'events' %}">Events</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'student-council' %}">Student Council</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                </li>
            </ul>
        </div>
    </nav>

templates/student-council.html
{% extends "base.html" %}
{% block title %}
Student Council
{% endblock title %}
{% block content %}

<div class="main-content text-size">
    <span class="heading-1"><b>Student Council</b></span><br>
    {% for i in studentCouncil %} {% if forloop.counter|divisibleby:"4" %}
    <br> {% endif %}
    <div style="display:inline-block;">
        <img src="{{ i.image.url }}" style="height:400px;width:400px;padding:30px;"><br>
     <b>
        {{ i.name }}
     </b><br>
       <span class="text-size-small">{{ i.get_position_display }}</span>
    </div>
    {% endfor %}
    <br>
    <br>
    {% if designTeam %}
    <span class="heading-1"><b>Design Team</b></span><br>
    {% for i in designTeam %} 
    <div style="display: inline-block;">
        <img src="{{ i.image.url }}" style="height: 400px;width:400px;padding:30px;"><br>
     <b>
        {{ i.name }}
     </b><br>
       <span class="text-size-small">{{ i.get_position_display }}</span>
    </div>
    {% if forloop.first %}
    <br> {% endif %}
    {% endfor %}
    {% endif %}
</div>
{% endblock %}
   